[package]
name = "chacc"
version = "0.1.0"
edition = "2024"

[dependencies]
hexf-parse = "0.2"
lexopt = "0.3"
libc = "0.2"
line-index = "0.1"
rustc-hash = "2"
smol_str = "0.3"
strum = { version = "0.28", features = ["derive"] }
thiserror = "2"
temp-dir = "0.2"
unicode-width = "0.2"
which = "8"

[build-dependencies]
xxhash-rust = { version = "0.8", features = ["xxh3", "std"] }

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "z"
panic = "abort"
strip = true
